"
Copyright 2026 Georg Hagn
SPDX-License-Identifier: Apache-2.0

I am a lightweight **JSON-RPC 2.0 over WebSocket** framework.

I provide the building blocks for communicating Smalltalk nodes over WebSockets. A node can act as both **client and server**, allowing bidirectional request/response communication between peers.
"
Class {
	#name : 'ManifestNexUtilsP2P',
	#superclass : 'PackageManifest',
	#category : 'NexUtils-P2P-Manifest',
	#package : 'NexUtils-P2P',
	#tag : 'Manifest'
}
